Unconditionally prune on fetches
Pruning is not enabled by default for git because it is technically
destructive, but in practice noone really cares if we stomp all over
remote refs, especially because there are always tons and tons of
changes to remote refs in a ghstack workflow.

In return, we never have a situation where fetch fails because someone
did something naughty to a remote ref that git refuses to update, e.g.,
and error like:

```
error: cannot lock ref 'refs/remotes/origin/opinfo/one_hot': 'refs/remotes/origin/opinfo' exists; cannot create 'refs/remotes/origin/opinfo/one_hot'
 ! [new branch]            opinfo/one_hot          -> origin/opinfo/one_hot  (unable to update local ref)
 ```

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

[ghstack-poisoned]